import { createDocument } from 'zod-openapi';
import { ZodOpenapiExample } from '../interfaces/zod-openapi-example';
import { AuthSchema } from '../schemas/auth';
import { CartSchema } from '../schemas/cart';
import { CategorySchema } from '../schemas/category';
import { ProductSchema } from '../schemas/product';
import { ProductCartSchema } from '../schemas/product-cart';

const schemas = {
  auth: {
    register: AuthSchema.register().body,
    login: AuthSchema.login().body,
  },
  category: {
    get: CategorySchema.get().params,
    getAll: CategorySchema.getAll().body,
    create: CategorySchema.create().body,
    update: CategorySchema.update(),
    delete: CategorySchema.delete().params,
  },
  product: {
    get: ProductSchema.get().params,
    getAll: ProductSchema.getAll().body,
    create: ProductSchema.create().body,
    update: ProductSchema.update(),
    delete: ProductSchema.delete().params,
  },
  cart: {
    get: CartSchema.get().params,
    update: CartSchema.update(),
    delete: CartSchema.delete().params,
  },
  productCart: {
    get: ProductCartSchema.get().params,
    create: ProductCartSchema.create().body,
    update: ProductCartSchema.update(),
    delete: ProductCartSchema.delete().params,
  },
};

const createResponse = (status: number, description: string, example: ZodOpenapiExample) => ({
  [status]: {
    description,
    content: {
      'application/json': {
        example,
      },
    },
  },
});

const commonResponses = {
  validationError: createResponse(400, 'Validation error or Database error', {
    error: true,
    message: 'Validation error',
    description: [{ path: ['field'], message: 'Expected type, received type' }],
  }),
  authError: createResponse(401, 'Authentication error', {
    error: true,
    message: 'No token provided, Invalid token or Token has expired',
  }),
  serverError: createResponse(500, 'Internal Server Error', {
    error: true,
    message: 'Internal Server Error',
  }),
};

const document = createDocument({
  openapi: '3.1.0',
  info: {
    title: 'FlickBox',
    version: '1.0.0',
    description: 'API documentation for FlickBox',
    contact: {
      name: 'API Support',
      email: 'nicolasbobone@gmail.com',
    },
  },
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        description: 'JWT Authorization header using the Bearer scheme.',
      },
    },
  },
  paths: {
    // AUTH
    '/auth/register': {
      post: {
        summary: 'User register',
        tags: ['AUTH'],
        requestBody: {
          required: true,
          content: { 'application/json': { schema: schemas.auth.register } },
        },
        responses: {
          ...createResponse(201, 'User successfully registered', {
            error: false,
            data: {
              id: 1,
              email: 'jaimefulano@gmail.com',
              firstName: 'Jaime',
              lastName: 'Fulano',
              createdAt: '2024-07-21T15:49:08.551Z',
              updatedAt: '2024-07-21T15:49:08.551Z',
            },
          }),
          ...commonResponses.validationError,
          ...createResponse(401, 'User already exists', {
            error: true,
            message: 'User already exists',
          }),
          ...commonResponses.serverError,
        },
      },
    },
    '/auth/login': {
      post: {
        summary: 'User login',
        tags: ['AUTH'],
        requestBody: {
          required: true,
          content: { 'application/json': { schema: schemas.auth.login } },
        },
        responses: {
          ...createResponse(200, 'User successfully logged in', {
            error: false,
            data: {
              user: {
                id: 1,
                email: 'jaimefulano@gmail.com',
                firstName: 'Jaime',
                lastName: 'Fulano',
                createdAt: '2024-07-21T02:54:16.798Z',
                updatedAt: '2024-07-21T02:54:16.798Z',
              },
              token: 'token',
            },
          }),
          ...commonResponses.validationError,
          ...createResponse(401, 'User does not exist or Incorrect credentials', {
            error: true,
            message: 'Incorrect credentials',
          }),
          ...commonResponses.serverError,
        },
      },
    },
    // CATEGORY
    '/category': {
      post: {
        summary: 'Get all categories',
        tags: ['CATEGORY'],
        requestBody: {
          content: {
            'application/json': { schema: schemas.category.getAll },
          },
        },
        responses: {
          ...createResponse(200, 'Categories successfully retrieved', {
            error: false,
            data: [
              {
                id: 1,
                name: 'LIBROS',
                createdAt: '2024-07-20T08:22:57.459Z',
                updatedAt: '2024-07-20T08:22:57.459Z',
              },
              {
                id: 2,
                name: 'COMPUTADORAS',
                createdAt: '2024-07-21T08:22:57.459Z',
                updatedAt: '2024-07-21T08:22:57.459Z',
              },
            ],
          }),
          ...createResponse(400, 'Database error', {
            error: true,
            message: 'Database error',
            description: 'Failed to fetch all categories',
          }),
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
    },
    '/category/create': {
      post: {
        summary: 'Register a category',
        tags: ['CATEGORY'],
        requestBody: {
          required: true,
          content: {
            'application/json': { schema: schemas.category.create },
          },
        },
        responses: {
          ...createResponse(201, 'Category successfully registered', {
            error: false,
            data: {
              id: 1,
              name: 'LIBROS',
              createdAt: '2024-07-20T08:22:57.459Z',
              updatedAt: '2024-07-20T08:22:57.459Z',
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
    },
    '/category/{id}': {
      get: {
        summary: 'Get a category',
        tags: ['CATEGORY'],
        requestParams: {
          header: schemas.category.get,
        },
        responses: {
          ...createResponse(200, 'Category successfully retrieved', {
            error: false,
            data: {
              id: 1,
              name: 'LIBROS',
              createdAt: '2024-07-20T08:22:57.459Z',
              updatedAt: '2024-07-20T08:22:57.459Z',
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
      put: {
        summary: 'Update a category',
        tags: ['CATEGORY'],
        requestParams: {
          header: schemas.category.update.params,
        },
        requestBody: {
          required: true,
          content: {
            'application/json': { schema: schemas.category.update.body },
          },
        },
        responses: {
          ...createResponse(200, 'Category successfully updated', {
            error: false,
            data: {
              id: 1,
              name: 'LIBROS',
              createdAt: '2024-07-20T08:22:57.459Z',
              updatedAt: '2024-07-20T08:22:57.459Z',
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
      delete: {
        summary: 'Delete a category',
        tags: ['CATEGORY'],
        requestParams: {
          header: schemas.category.delete,
        },
        responses: {
          ...createResponse(200, 'Category successfully deleted', {
            error: false,
            data: {
              id: 1,
              name: 'LIBROS',
              createdAt: '2024-07-20T08:22:57.459Z',
              updatedAt: '2024-07-20T08:22:57.459Z',
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
    },
    // PRODUCT
    '/product': {
      post: {
        summary: 'Get all products',
        tags: ['PRODUCT'],
        requestBody: {
          content: {
            'application/json': { schema: schemas.product.getAll },
          },
        },
        responses: {
          ...createResponse(200, 'Products successfully retrieved', {
            error: false,
            data: [
              {
                id: 1,
                name: 'Clean code JS',
                description: 'Mejora tu código con este gran libro.',
                sku: '19414ea4-879e-4213-a182-8774f21a01c6',
                price: 100,
                categoryId: 1,
                createdAt: '2024-08-10T00:14:57.023Z',
                updatedAt: '2024-08-10T00:14:57.023Z',
                category: {
                  id: 1,
                  name: 'LIBROS',
                  description: null,
                  createdAt: '2024-08-10T00:14:44.355Z',
                  updatedAt: '2024-08-10T00:14:44.355Z',
                },
              },
              {
                id: 2,
                name: 'MacBook Pro',
                description: 'Computadora portátil',
                sku: '835df238-b19e-4cd4-aa3b-d7c3f74ac779',
                price: 100,
                categoryId: 2,
                createdAt: '2024-08-10T04:33:13.700Z',
                updatedAt: '2024-08-10T04:33:13.700Z',
                category: {
                  id: 1,
                  name: 'COMPUTADORAS',
                  description: null,
                  createdAt: '2024-08-10T00:14:44.355Z',
                  updatedAt: '2024-08-10T00:14:44.355Z',
                },
              },
            ],
          }),
          ...createResponse(400, 'Database error', {
            error: true,
            message: 'Database error',
            description: 'Failed to fetch all products',
          }),
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
    },
    '/product/create': {
      post: {
        summary: 'Register a product',
        tags: ['PRODUCT'],
        requestBody: {
          required: true,
          content: {
            'application/json': { schema: schemas.product.create },
          },
        },
        responses: {
          ...createResponse(201, 'Products successfully registered', {
            error: false,
            data: {
              id: 5,
              name: 'Clean code JS',
              description: 'Mejora tu código con este gran libro.',
              sku: '835df238-b19e-4cd4-aa3b-d7c3f74ac779',
              price: 100,
              categoryId: 1,
              createdAt: '2024-08-10T04:33:13.700Z',
              updatedAt: '2024-08-10T04:33:13.700Z',
              category: {
                id: 1,
                name: 'LIBROS',
                description: null,
                createdAt: '2024-08-10T00:14:44.355Z',
                updatedAt: '2024-08-10T00:14:44.355Z',
              },
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
    },
    '/product/{id}': {
      get: {
        summary: 'Get a product',
        tags: ['PRODUCT'],
        requestParams: {
          header: schemas.product.get,
        },
        responses: {
          ...createResponse(200, 'Product successfully retrieved', {
            error: false,
            data: {
              id: 5,
              name: 'Clean code JS',
              description: 'Mejora tu código con este gran libro.',
              sku: '835df238-b19e-4cd4-aa3b-d7c3f74ac779',
              price: 100,
              categoryId: 1,
              createdAt: '2024-08-10T04:33:13.700Z',
              updatedAt: '2024-08-10T04:33:13.700Z',
              category: {
                id: 1,
                name: 'LIBROS',
                description: null,
                createdAt: '2024-08-10T00:14:44.355Z',
                updatedAt: '2024-08-10T00:14:44.355Z',
              },
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
      put: {
        summary: 'Update a product',
        tags: ['PRODUCT'],
        requestParams: {
          header: schemas.product.update.params,
        },
        requestBody: {
          required: true,
          content: {
            'application/json': { schema: schemas.product.update.body },
          },
        },
        responses: {
          ...createResponse(200, 'Product successfully updated', {
            error: false,
            data: {
              id: 5,
              name: 'Clean code JS',
              description: 'Mejora tu código con este gran libro.',
              sku: '835df238-b19e-4cd4-aa3b-d7c3f74ac779',
              price: 100,
              categoryId: 1,
              createdAt: '2024-08-10T04:33:13.700Z',
              updatedAt: '2024-08-11T04:33:13.700Z',
              category: {
                id: 1,
                name: 'LIBROS',
                description: null,
                createdAt: '2024-08-10T00:14:44.355Z',
                updatedAt: '2024-08-10T00:14:44.355Z',
              },
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
      delete: {
        summary: 'Delete a product',
        tags: ['PRODUCT'],
        requestParams: {
          header: schemas.product.delete,
        },
        responses: {
          ...createResponse(200, 'Product successfully deleted', {
            error: false,
            data: {
              id: 5,
              name: 'Clean code JS',
              description: 'Mejora tu código con este gran libro.',
              sku: '835df238-b19e-4cd4-aa3b-d7c3f74ac779',
              price: 100,
              categoryId: 1,
              createdAt: '2024-08-10T04:33:13.700Z',
              updatedAt: '2024-08-10T04:33:13.700Z',
              category: {
                id: 1,
                name: 'LIBROS',
                description: null,
                createdAt: '2024-08-10T00:14:44.355Z',
                updatedAt: '2024-08-11T00:14:44.355Z',
              },
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
    },
    // CART
    '/cart': {
      get: {
        summary: 'Get all carts',
        tags: ['CART'],
        responses: {
          ...createResponse(200, 'Carts successfully retrieved', {
            error: false,
            data: [
              {
                id: 1,
                userId: 1,
                status: 'pending',
                createdAt: '2024-08-10T20:58:05.507Z',
                updatedAt: '2024-08-10T20:58:05.507Z',
                products: [
                  {
                    id: 1,
                    productId: 1,
                    cartId: 1,
                    quantity: 1,
                    createdAt: '2024-08-10T20:59:50.974Z',
                    updatedAt: '2024-08-10T20:59:50.974Z',
                    product: {
                      id: 1,
                      name: 'Clean code JS',
                      description: 'Mejora tu código con este gran libro.',
                      sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                      price: 100,
                      categoryId: 1,
                      createdAt: '2024-08-10T21:49:26.804Z',
                      updatedAt: '2024-08-10T21:49:26.804Z',
                    },
                  },
                  {
                    id: 2,
                    productId: 2,
                    cartId: 1,
                    quantity: 2,
                    createdAt: '2024-08-10T21:51:57.586Z',
                    updatedAt: '2024-08-10T21:51:57.586Z',
                    product: {
                      id: 2,
                      name: 'MacBook Pro',
                      description: 'La mejor computadora del mercado.',
                      sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                      price: 2000,
                      categoryId: 2,
                      createdAt: '2024-08-10T22:08:36.653Z',
                      updatedAt: '2024-08-10T22:08:36.653Z',
                    },
                  },
                ],
              },
              {
                id: 2,
                userId: 1,
                status: 'completed',
                createdAt: '2024-08-11T17:07:26.277Z',
                updatedAt: '2024-08-11T17:07:26.277Z',
                products: [
                  {
                    id: 3,
                    productId: 2,
                    cartId: 2,
                    quantity: 3,
                    createdAt: '2024-08-11T17:08:13.110Z',
                    updatedAt: '2024-08-11T17:08:13.110Z',
                    product: {
                      id: 2,
                      name: 'Macbook Pro',
                      description: 'La mejor computadora del mercado.',
                      sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                      price: 2000,
                      categoryId: 2,
                      createdAt: '2024-08-10T22:08:36.653Z',
                      updatedAt: '2024-08-10T22:08:36.653Z',
                    },
                  },
                ],
              },
              {
                id: 3,
                userId: 1,
                status: 'canceled',
                createdAt: '2024-08-11T17:07:41.042Z',
                updatedAt: '2024-08-11T17:07:41.042Z',
                products: [],
              },
            ],
          }),
          ...createResponse(400, 'Database error', {
            error: true,
            message: 'Database error',
            description: 'Failed to fetch all carts',
          }),
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
      post: {
        summary: 'Register a cart',
        tags: ['CART'],
        responses: {
          ...createResponse(201, 'Carts successfully registered', {
            error: false,
            data: {
              id: 1,
              userId: 1,
              status: 'pending',
              createdAt: '2024-08-10T20:58:05.507Z',
              updatedAt: '2024-08-10T20:58:05.507Z',
              products: [
                {
                  id: 1,
                  productId: 1,
                  cartId: 1,
                  quantity: 1,
                  createdAt: '2024-08-10T20:59:50.974Z',
                  updatedAt: '2024-08-10T20:59:50.974Z',
                  product: {
                    id: 1,
                    name: 'Clean code JS',
                    description: 'Mejora tu código con este gran libro.',
                    sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                    price: 100,
                    categoryId: 1,
                    createdAt: '2024-08-10T21:49:26.804Z',
                    updatedAt: '2024-08-10T21:49:26.804Z',
                  },
                },
                {
                  id: 2,
                  productId: 2,
                  cartId: 1,
                  quantity: 2,
                  createdAt: '2024-08-10T21:51:57.586Z',
                  updatedAt: '2024-08-10T21:51:57.586Z',
                  product: {
                    id: 2,
                    name: 'MacBook Pro',
                    description: 'La mejor computadora del mercado.',
                    sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                    price: 2000,
                    categoryId: 2,
                    createdAt: '2024-08-10T22:08:36.653Z',
                    updatedAt: '2024-08-10T22:08:36.653Z',
                  },
                },
              ],
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
    },
    '/cart/pending': {
      get: {
        summary: 'Get a pending cart',
        tags: ['CART'],
        responses: {
          ...createResponse(200, 'Cart successfully retrieved', {
            error: false,
            data: {
              id: 1,
              userId: 1,
              status: 'pending',
              createdAt: '2024-08-10T20:58:05.507Z',
              updatedAt: '2024-08-10T20:58:05.507Z',
              products: [
                {
                  productId: 1,
                  cartId: 1,
                  quantity: 1,
                  createdAt: '2024-08-10T20:59:50.974Z',
                  updatedAt: '2024-08-10T20:59:50.974Z',
                  product: {
                    id: 1,
                    name: 'Clean code JS',
                    description: 'Mejora tu código con este gran libro.',
                    sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                    price: 100,
                    categoryId: 1,
                    createdAt: '2024-08-10T21:49:26.804Z',
                    updatedAt: '2024-08-10T21:49:26.804Z',
                  },
                },
                {
                  productId: 2,
                  cartId: 1,
                  quantity: 2,
                  createdAt: '2024-08-10T21:51:57.586Z',
                  updatedAt: '2024-08-10T21:51:57.586Z',
                  product: {
                    id: 2,
                    name: 'MacBook Pro',
                    description: 'La mejor computadora del mercado.',
                    sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                    price: 2000,
                    categoryId: 2,
                    createdAt: '2024-08-10T22:08:36.653Z',
                    updatedAt: '2024-08-10T22:08:36.653Z',
                  },
                },
              ],
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
    },
    '/cart/{id}': {
      get: {
        summary: 'Get a cart',
        tags: ['CART'],
        requestParams: {
          header: schemas.cart.get,
        },
        responses: {
          ...createResponse(200, 'Cart successfully retrieved', {
            error: false,
            data: {
              id: 1,
              userId: 1,
              status: 'pending',
              createdAt: '2024-08-10T20:58:05.507Z',
              updatedAt: '2024-08-10T20:58:05.507Z',
              products: [
                {
                  id: 1,
                  productId: 1,
                  cartId: 1,
                  quantity: 1,
                  createdAt: '2024-08-10T20:59:50.974Z',
                  updatedAt: '2024-08-10T20:59:50.974Z',
                  product: {
                    id: 1,
                    name: 'Clean code JS',
                    description: 'Mejora tu código con este gran libro.',
                    sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                    price: 100,
                    categoryId: 1,
                    createdAt: '2024-08-10T21:49:26.804Z',
                    updatedAt: '2024-08-10T21:49:26.804Z',
                  },
                },
                {
                  id: 2,
                  productId: 2,
                  cartId: 1,
                  quantity: 2,
                  createdAt: '2024-08-10T21:51:57.586Z',
                  updatedAt: '2024-08-10T21:51:57.586Z',
                  product: {
                    id: 2,
                    name: 'MacBook Pro',
                    description: 'La mejor computadora del mercado.',
                    sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                    price: 2000,
                    categoryId: 2,
                    createdAt: '2024-08-10T22:08:36.653Z',
                    updatedAt: '2024-08-10T22:08:36.653Z',
                  },
                },
              ],
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
      put: {
        summary: 'Update a cart',
        tags: ['CART'],
        requestParams: {
          header: schemas.cart.update.params,
        },
        requestBody: {
          required: true,
          content: {
            'application/json': { schema: schemas.product.update.body },
          },
        },
        responses: {
          ...createResponse(200, 'Cart successfully updated', {
            error: false,
            data: {
              id: 1,
              userId: 1,
              status: 'pending',
              createdAt: '2024-08-10T20:58:05.507Z',
              updatedAt: '2024-08-10T20:58:05.507Z',
              products: [
                {
                  id: 1,
                  productId: 1,
                  cartId: 1,
                  quantity: 1,
                  createdAt: '2024-08-10T20:59:50.974Z',
                  updatedAt: '2024-08-10T20:59:50.974Z',
                  product: {
                    id: 1,
                    name: 'Clean code JS',
                    description: 'Mejora tu código con este gran libro.',
                    sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                    price: 100,
                    categoryId: 1,
                    createdAt: '2024-08-10T21:49:26.804Z',
                    updatedAt: '2024-08-10T21:49:26.804Z',
                  },
                },
                {
                  id: 2,
                  productId: 2,
                  cartId: 1,
                  quantity: 2,
                  createdAt: '2024-08-10T21:51:57.586Z',
                  updatedAt: '2024-08-10T21:51:57.586Z',
                  product: {
                    id: 2,
                    name: 'MacBook Pro',
                    description: 'La mejor computadora del mercado.',
                    sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                    price: 2000,
                    categoryId: 2,
                    createdAt: '2024-08-10T22:08:36.653Z',
                    updatedAt: '2024-08-10T22:08:36.653Z',
                  },
                },
              ],
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
      delete: {
        summary: 'Delete a cart',
        tags: ['CART'],
        requestParams: {
          header: schemas.cart.delete,
        },
        responses: {
          ...createResponse(200, 'Cart successfully deleted', {
            error: false,
            data: {
              id: 1,
              userId: 1,
              status: 'pending',
              createdAt: '2024-08-10T20:58:05.507Z',
              updatedAt: '2024-08-10T20:58:05.507Z',
              products: [
                {
                  id: 1,
                  productId: 1,
                  cartId: 1,
                  quantity: 1,
                  createdAt: '2024-08-10T20:59:50.974Z',
                  updatedAt: '2024-08-10T20:59:50.974Z',
                  product: {
                    id: 1,
                    name: 'Clean code JS',
                    description: 'Mejora tu código con este gran libro.',
                    sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                    price: 100,
                    categoryId: 1,
                    createdAt: '2024-08-10T21:49:26.804Z',
                    updatedAt: '2024-08-10T21:49:26.804Z',
                  },
                },
                {
                  id: 2,
                  productId: 2,
                  cartId: 1,
                  quantity: 2,
                  createdAt: '2024-08-10T21:51:57.586Z',
                  updatedAt: '2024-08-10T21:51:57.586Z',
                  product: {
                    id: 2,
                    name: 'MacBook Pro',
                    description: 'La mejor computadora del mercado.',
                    sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                    price: 2000,
                    categoryId: 2,
                    createdAt: '2024-08-10T22:08:36.653Z',
                    updatedAt: '2024-08-10T22:08:36.653Z',
                  },
                },
              ],
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
    },
    // PRODUCT-CART
    '/product-cart': {
      get: {
        summary: 'Get all product carts',
        tags: ['PRODUCT-CART'],
        responses: {
          ...createResponse(200, 'Product carts successfully retrieved', {
            error: false,
            data: [
              {
                id: 1,
                productId: 1,
                cartId: 1,
                quantity: 1,
                createdAt: '2024-08-10T20:59:50.974Z',
                updatedAt: '2024-08-10T20:59:50.974Z',
                product: {
                  id: 1,
                  name: 'Clean code JS',
                  description: 'Mejora tu código con este gran libro.',
                  sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                  price: 100,
                  categoryId: 1,
                  createdAt: '2024-08-10T21:49:26.804Z',
                  updatedAt: '2024-08-10T21:49:26.804Z',
                },
                cart: {
                  id: 1,
                  userId: 1,
                  status: 'pending',
                  createdAt: '2024-08-10T20:58:05.507Z',
                  updatedAt: '2024-08-10T20:58:05.507Z',
                  products: [
                    {
                      id: 1,
                      productId: 1,
                      cartId: 1,
                      quantity: 1,
                      createdAt: '2024-08-10T20:59:50.974Z',
                      updatedAt: '2024-08-10T20:59:50.974Z',
                      product: {
                        id: 1,
                        name: 'Clean code JS',
                        description: 'Mejora tu código con este gran libro.',
                        sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                        price: 100,
                        categoryId: 1,
                        createdAt: '2024-08-10T21:49:26.804Z',
                        updatedAt: '2024-08-10T21:49:26.804Z',
                      },
                    },
                    {
                      id: 2,
                      productId: 2,
                      cartId: 1,
                      quantity: 2,
                      createdAt: '2024-08-10T21:51:57.586Z',
                      updatedAt: '2024-08-10T21:51:57.586Z',
                      product: {
                        id: 2,
                        name: 'Macbook Pro',
                        description: 'La mejor computadora del mercado.',
                        sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                        price: 2000,
                        categoryId: 2,
                        createdAt: '2024-08-10T22:08:36.653Z',
                        updatedAt: '2024-08-10T22:08:36.653Z',
                      },
                    },
                    {
                      id: 6,
                      productId: 1,
                      cartId: 1,
                      quantity: 1,
                      createdAt: '2024-08-11T21:38:05.112Z',
                      updatedAt: '2024-08-11T21:38:05.112Z',
                      product: {
                        id: 1,
                        name: 'Clean code JS',
                        description: 'Mejora tu código con este gran libro.',
                        sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                        price: 100,
                        categoryId: 1,
                        createdAt: '2024-08-10T21:49:26.804Z',
                        updatedAt: '2024-08-10T21:49:26.804Z',
                      },
                    },
                  ],
                },
              },
              {
                id: 2,
                productId: 2,
                cartId: 1,
                quantity: 2,
                createdAt: '2024-08-10T21:51:57.586Z',
                updatedAt: '2024-08-10T21:51:57.586Z',
                product: {
                  id: 2,
                  name: 'Macbook Pro',
                  description: 'La mejor computadora del mercado.',
                  sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                  price: 2000,
                  categoryId: 2,
                  createdAt: '2024-08-10T22:08:36.653Z',
                  updatedAt: '2024-08-10T22:08:36.653Z',
                },
                cart: {
                  id: 1,
                  userId: 1,
                  status: 'pending',
                  createdAt: '2024-08-10T20:58:05.507Z',
                  updatedAt: '2024-08-10T20:58:05.507Z',
                  products: [
                    {
                      id: 1,
                      productId: 1,
                      cartId: 1,
                      quantity: 1,
                      createdAt: '2024-08-10T20:59:50.974Z',
                      updatedAt: '2024-08-10T20:59:50.974Z',
                      product: {
                        id: 1,
                        name: 'Clean code JS',
                        description: 'Mejora tu código con este gran libro.',
                        sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                        price: 100,
                        categoryId: 1,
                        createdAt: '2024-08-10T21:49:26.804Z',
                        updatedAt: '2024-08-10T21:49:26.804Z',
                      },
                    },
                    {
                      id: 2,
                      productId: 2,
                      cartId: 1,
                      quantity: 2,
                      createdAt: '2024-08-10T21:51:57.586Z',
                      updatedAt: '2024-08-10T21:51:57.586Z',
                      product: {
                        id: 2,
                        name: 'Macbook Pro',
                        description: 'La mejor computadora del mercado.',
                        sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                        price: 2000,
                        categoryId: 2,
                        createdAt: '2024-08-10T22:08:36.653Z',
                        updatedAt: '2024-08-10T22:08:36.653Z',
                      },
                    },
                    {
                      id: 6,
                      productId: 1,
                      cartId: 1,
                      quantity: 1,
                      createdAt: '2024-08-11T21:38:05.112Z',
                      updatedAt: '2024-08-11T21:38:05.112Z',
                      product: {
                        id: 1,
                        name: 'Clean code JS',
                        description: 'Mejora tu código con este gran libro.',
                        sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                        price: 100,
                        categoryId: 1,
                        createdAt: '2024-08-10T21:49:26.804Z',
                        updatedAt: '2024-08-10T21:49:26.804Z',
                      },
                    },
                  ],
                },
              },
              {
                id: 3,
                productId: 2,
                cartId: 2,
                quantity: 3,
                createdAt: '2024-08-11T17:08:13.110Z',
                updatedAt: '2024-08-11T17:08:13.110Z',
                product: {
                  id: 2,
                  name: 'Macbook Pro',
                  description: 'La mejor computadora del mercado.',
                  sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                  price: 2000,
                  categoryId: 2,
                  createdAt: '2024-08-10T22:08:36.653Z',
                  updatedAt: '2024-08-10T22:08:36.653Z',
                },
                cart: {
                  id: 2,
                  userId: 1,
                  status: 'completed',
                  createdAt: '2024-08-11T17:07:26.277Z',
                  updatedAt: '2024-08-11T17:07:26.277Z',
                  products: [
                    {
                      id: 3,
                      productId: 2,
                      cartId: 2,
                      quantity: 3,
                      createdAt: '2024-08-11T17:08:13.110Z',
                      updatedAt: '2024-08-11T17:08:13.110Z',
                      product: {
                        id: 2,
                        name: 'Macbook Pro',
                        description: 'La mejor computadora del mercado.',
                        sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                        price: 2000,
                        categoryId: 2,
                        createdAt: '2024-08-10T22:08:36.653Z',
                        updatedAt: '2024-08-10T22:08:36.653Z',
                      },
                    },
                  ],
                },
              },
            ],
          }),
          ...createResponse(400, 'Database error', {
            error: true,
            message: 'Database error',
            description: 'Failed to fetch all product carts',
          }),
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
      post: {
        summary: 'Register a product cart',
        tags: ['PRODUCT-CART'],
        requestBody: {
          required: true,
          content: {
            'application/json': { schema: schemas.productCart.create },
          },
        },
        responses: {
          ...createResponse(201, 'Product carts successfully registered', {
            error: false,
            data: {
              id: 1,
              productId: 1,
              cartId: 1,
              quantity: 1,
              createdAt: '2024-08-10T20:59:50.974Z',
              updatedAt: '2024-08-10T20:59:50.974Z',
              product: {
                id: 1,
                name: 'Clean code JS',
                description: 'Mejora tu código con este gran libro.',
                sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                price: 100,
                categoryId: 1,
                createdAt: '2024-08-10T21:49:26.804Z',
                updatedAt: '2024-08-10T21:49:26.804Z',
              },
              cart: {
                id: 1,
                userId: 1,
                status: 'pending',
                createdAt: '2024-08-10T20:58:05.507Z',
                updatedAt: '2024-08-10T20:58:05.507Z',
                products: [
                  {
                    id: 1,
                    productId: 1,
                    cartId: 1,
                    quantity: 1,
                    createdAt: '2024-08-10T20:59:50.974Z',
                    updatedAt: '2024-08-10T20:59:50.974Z',
                    product: {
                      id: 1,
                      name: 'Clean code JS',
                      description: 'Mejora tu código con este gran libro.',
                      sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                      price: 100,
                      categoryId: 1,
                      createdAt: '2024-08-10T21:49:26.804Z',
                      updatedAt: '2024-08-10T21:49:26.804Z',
                    },
                  },
                  {
                    id: 2,
                    productId: 2,
                    cartId: 1,
                    quantity: 2,
                    createdAt: '2024-08-10T21:51:57.586Z',
                    updatedAt: '2024-08-10T21:51:57.586Z',
                    product: {
                      id: 2,
                      name: 'Macbook Pro',
                      description: 'La mejor computadora del mercado.',
                      sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                      price: 2000,
                      categoryId: 2,
                      createdAt: '2024-08-10T22:08:36.653Z',
                      updatedAt: '2024-08-10T22:08:36.653Z',
                    },
                  },
                  {
                    id: 6,
                    productId: 1,
                    cartId: 1,
                    quantity: 1,
                    createdAt: '2024-08-11T21:38:05.112Z',
                    updatedAt: '2024-08-11T21:38:05.112Z',
                    product: {
                      id: 1,
                      name: 'Clean code JS',
                      description: 'Mejora tu código con este gran libro.',
                      sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                      price: 100,
                      categoryId: 1,
                      createdAt: '2024-08-10T21:49:26.804Z',
                      updatedAt: '2024-08-10T21:49:26.804Z',
                    },
                  },
                ],
              },
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
    },
    '/product-cart/{id}': {
      get: {
        summary: 'Get a product cart',
        tags: ['PRODUCT-CART'],
        requestParams: {
          header: schemas.productCart.get,
        },
        responses: {
          ...createResponse(200, 'Product cart successfully retrieved', {
            error: false,
            data: {
              id: 1,
              productId: 1,
              cartId: 1,
              quantity: 1,
              createdAt: '2024-08-10T20:59:50.974Z',
              updatedAt: '2024-08-10T20:59:50.974Z',
              product: {
                id: 1,
                name: 'Clean code JS',
                description: 'Mejora tu código con este gran libro.',
                sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                price: 100,
                categoryId: 1,
                createdAt: '2024-08-10T21:49:26.804Z',
                updatedAt: '2024-08-10T21:49:26.804Z',
              },
              cart: {
                id: 1,
                userId: 1,
                status: 'pending',
                createdAt: '2024-08-10T20:58:05.507Z',
                updatedAt: '2024-08-10T20:58:05.507Z',
                products: [
                  {
                    id: 1,
                    productId: 1,
                    cartId: 1,
                    quantity: 1,
                    createdAt: '2024-08-10T20:59:50.974Z',
                    updatedAt: '2024-08-10T20:59:50.974Z',
                    product: {
                      id: 1,
                      name: 'Clean code JS',
                      description: 'Mejora tu código con este gran libro.',
                      sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                      price: 100,
                      categoryId: 1,
                      createdAt: '2024-08-10T21:49:26.804Z',
                      updatedAt: '2024-08-10T21:49:26.804Z',
                    },
                  },
                  {
                    id: 2,
                    productId: 2,
                    cartId: 1,
                    quantity: 2,
                    createdAt: '2024-08-10T21:51:57.586Z',
                    updatedAt: '2024-08-10T21:51:57.586Z',
                    product: {
                      id: 2,
                      name: 'Macbook Pro',
                      description: 'La mejor computadora del mercado.',
                      sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                      price: 2000,
                      categoryId: 2,
                      createdAt: '2024-08-10T22:08:36.653Z',
                      updatedAt: '2024-08-10T22:08:36.653Z',
                    },
                  },
                  {
                    id: 6,
                    productId: 1,
                    cartId: 1,
                    quantity: 1,
                    createdAt: '2024-08-11T21:38:05.112Z',
                    updatedAt: '2024-08-11T21:38:05.112Z',
                    product: {
                      id: 1,
                      name: 'Clean code JS',
                      description: 'Mejora tu código con este gran libro.',
                      sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                      price: 100,
                      categoryId: 1,
                      createdAt: '2024-08-10T21:49:26.804Z',
                      updatedAt: '2024-08-10T21:49:26.804Z',
                    },
                  },
                ],
              },
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
      put: {
        summary: 'Update a product cart',
        tags: ['PRODUCT-CART'],
        requestParams: {
          header: schemas.productCart.update.params,
        },
        requestBody: {
          required: true,
          content: {
            'application/json': { schema: schemas.productCart.update.body },
          },
        },
        responses: {
          ...createResponse(200, 'Product cart successfully updated', {
            error: false,
            data: {
              id: 1,
              productId: 1,
              cartId: 1,
              quantity: 1,
              createdAt: '2024-08-10T20:59:50.974Z',
              updatedAt: '2024-08-10T20:59:50.974Z',
              product: {
                id: 1,
                name: 'Clean code JS',
                description: 'Mejora tu código con este gran libro.',
                sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                price: 100,
                categoryId: 1,
                createdAt: '2024-08-10T21:49:26.804Z',
                updatedAt: '2024-08-10T21:49:26.804Z',
              },
              cart: {
                id: 1,
                userId: 1,
                status: 'pending',
                createdAt: '2024-08-10T20:58:05.507Z',
                updatedAt: '2024-08-10T20:58:05.507Z',
                products: [
                  {
                    id: 1,
                    productId: 1,
                    cartId: 1,
                    quantity: 1,
                    createdAt: '2024-08-10T20:59:50.974Z',
                    updatedAt: '2024-08-10T20:59:50.974Z',
                    product: {
                      id: 1,
                      name: 'Clean code JS',
                      description: 'Mejora tu código con este gran libro.',
                      sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                      price: 100,
                      categoryId: 1,
                      createdAt: '2024-08-10T21:49:26.804Z',
                      updatedAt: '2024-08-10T21:49:26.804Z',
                    },
                  },
                  {
                    id: 2,
                    productId: 2,
                    cartId: 1,
                    quantity: 2,
                    createdAt: '2024-08-10T21:51:57.586Z',
                    updatedAt: '2024-08-10T21:51:57.586Z',
                    product: {
                      id: 2,
                      name: 'Macbook Pro',
                      description: 'La mejor computadora del mercado.',
                      sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                      price: 2000,
                      categoryId: 2,
                      createdAt: '2024-08-10T22:08:36.653Z',
                      updatedAt: '2024-08-10T22:08:36.653Z',
                    },
                  },
                  {
                    id: 6,
                    productId: 1,
                    cartId: 1,
                    quantity: 1,
                    createdAt: '2024-08-11T21:38:05.112Z',
                    updatedAt: '2024-08-11T21:38:05.112Z',
                    product: {
                      id: 1,
                      name: 'Clean code JS',
                      description: 'Mejora tu código con este gran libro.',
                      sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                      price: 100,
                      categoryId: 1,
                      createdAt: '2024-08-10T21:49:26.804Z',
                      updatedAt: '2024-08-10T21:49:26.804Z',
                    },
                  },
                ],
              },
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
      delete: {
        summary: 'Delete a cart',
        tags: ['PRODUCT-CART'],
        requestParams: {
          header: schemas.productCart.delete,
        },
        responses: {
          ...createResponse(200, 'Cart successfully deleted', {
            error: false,
            data: {
              id: 1,
              productId: 1,
              cartId: 1,
              quantity: 1,
              createdAt: '2024-08-10T20:59:50.974Z',
              updatedAt: '2024-08-10T20:59:50.974Z',
              product: {
                id: 1,
                name: 'Clean code JS',
                description: 'Mejora tu código con este gran libro.',
                sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                price: 100,
                categoryId: 1,
                createdAt: '2024-08-10T21:49:26.804Z',
                updatedAt: '2024-08-10T21:49:26.804Z',
              },
              cart: {
                id: 1,
                userId: 1,
                status: 'pending',
                createdAt: '2024-08-10T20:58:05.507Z',
                updatedAt: '2024-08-10T20:58:05.507Z',
                products: [
                  {
                    id: 1,
                    productId: 1,
                    cartId: 1,
                    quantity: 1,
                    createdAt: '2024-08-10T20:59:50.974Z',
                    updatedAt: '2024-08-10T20:59:50.974Z',
                    product: {
                      id: 1,
                      name: 'Clean code JS',
                      description: 'Mejora tu código con este gran libro.',
                      sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                      price: 100,
                      categoryId: 1,
                      createdAt: '2024-08-10T21:49:26.804Z',
                      updatedAt: '2024-08-10T21:49:26.804Z',
                    },
                  },
                  {
                    id: 2,
                    productId: 2,
                    cartId: 1,
                    quantity: 2,
                    createdAt: '2024-08-10T21:51:57.586Z',
                    updatedAt: '2024-08-10T21:51:57.586Z',
                    product: {
                      id: 2,
                      name: 'Macbook Pro',
                      description: 'La mejor computadora del mercado.',
                      sku: 'cec21f32-58b3-41d9-bf1a-1af049ac0560',
                      price: 2000,
                      categoryId: 2,
                      createdAt: '2024-08-10T22:08:36.653Z',
                      updatedAt: '2024-08-10T22:08:36.653Z',
                    },
                  },
                  {
                    id: 6,
                    productId: 1,
                    cartId: 1,
                    quantity: 1,
                    createdAt: '2024-08-11T21:38:05.112Z',
                    updatedAt: '2024-08-11T21:38:05.112Z',
                    product: {
                      id: 1,
                      name: 'Clean code JS',
                      description: 'Mejora tu código con este gran libro.',
                      sku: '7a26c0a2-8cdb-4368-8373-c5c27debbd53',
                      price: 100,
                      categoryId: 1,
                      createdAt: '2024-08-10T21:49:26.804Z',
                      updatedAt: '2024-08-10T21:49:26.804Z',
                    },
                  },
                ],
              },
            },
          }),
          ...commonResponses.validationError,
          ...commonResponses.authError,
          ...commonResponses.serverError,
        },
      },
    },
  },
  security: [
    {
      bearerAuth: [],
    },
  ],
});

export { document };
